In [1]:
import numpy as np
from diagonal import Diagonal
import scipy.linalg as la
import scipy

#### Create an instance of A
We will use a small value of n and d for readability purposes

* n=3
* d =2

In [2]:
diag = Diagonal(3,2)

Lets compare the standard vs dense representation and include the basis vectors

In [3]:
print(diag.matrix,diag.from_dense(diag.matrix),diag.basis,sep='\n\n')

[[ 1.68209386  0.18537211  0.51384634]
 [ 0.64829105 -1.25461459 -0.16189788]
 [ 0.12170741  0.22680394 -0.73704976]
 [ 0.70052075 -1.22226286 -0.73490155]
 [-0.46464491 -1.83254945 -0.24030872]
 [-0.22186881 -1.39994133  0.15954438]]

[[ 1.68209386  0.          0.18537211  0.          0.51384634  0.        ]
 [ 0.          0.64829105  0.         -1.25461459  0.         -0.16189788]
 [ 0.12170741  0.          0.22680394  0.         -0.73704976  0.        ]
 [ 0.          0.70052075  0.         -1.22226286  0.         -0.73490155]
 [-0.46464491  0.         -1.83254945  0.         -0.24030872  0.        ]
 [ 0.         -0.22186881  0.         -1.39994133  0.          0.15954438]]

[array([0, 2, 4]), array([1, 3, 5])]


As seen, every other row in the dense representation corresponds to every other column in A



#### Matrix multiplication

In [4]:
x = np.random.randn(6,6).astype(np.float)
sparse = diag.from_dense(diag.matrix)
dense_mm = diag.mm(x)
sparse_mm = np.dot(sparse,x)

In [5]:
print(dense_mm,sparse_mm,np.allclose(dense_mm,sparse_mm),sep='\n\n')

[[ 1.27755207  1.61975335  0.17166713  0.45347977 -1.57522138 -0.54138693]
 [ 1.60135554 -0.37317055  1.58197813  0.00633124  0.25944916 -0.73678153]
 [-0.47982576  0.60117021 -0.61218137  0.71784172  1.19347276  0.11817397]
 [ 1.90153165 -0.43495582  1.24213135  0.12795045  0.09312017 -1.56199765]
 [ 2.89518543  0.10759587  0.77742783  1.12412282 -1.74117891  0.04048377]
 [ 0.04238638 -0.19393153  2.13005947 -0.46472496 -0.10578554 -0.08299327]]

[[ 1.27755207  1.61975335  0.17166713  0.45347977 -1.57522138 -0.54138693]
 [ 1.60135554 -0.37317055  1.58197813  0.00633124  0.25944916 -0.73678153]
 [-0.47982576  0.60117021 -0.61218137  0.71784172  1.19347276  0.11817397]
 [ 1.90153165 -0.43495582  1.24213135  0.12795045  0.09312017 -1.56199765]
 [ 2.89518543  0.10759587  0.77742783  1.12412282 -1.74117891  0.04048377]
 [ 0.04238638 -0.19393153  2.13005947 -0.46472496 -0.10578554 -0.08299327]]

True


Left matrix multiplication is also possible

In [6]:
dense_mm = diag.mm(x,left=True)
sparse_mm = np.dot(x,sparse)
print(dense_mm,sparse_mm,np.allclose(dense_mm,sparse_mm),sep='\n\n')

[[ 1.80488102  1.3088895   1.38659953 -1.94375973  0.6540345  -0.72764114]
 [ 2.59276838  0.23973661 -0.722425    0.08349524  0.9002134  -0.33528254]
 [-3.7514455  -0.64299902 -2.82741584  1.02806984 -0.88630058  0.52791182]
 [-0.76771045  0.22977988 -0.44138948 -0.89628949  0.87157363 -0.16637099]
 [ 1.09217155 -1.15719505  2.63534405  2.43357403 -0.05327339  0.86451469]
 [-0.75089166 -0.363482   -0.58530784 -1.93498898 -0.64481942  0.3283395 ]]

[[ 1.80488102  1.3088895   1.38659953 -1.94375973  0.6540345  -0.72764114]
 [ 2.59276838  0.23973661 -0.722425    0.08349524  0.9002134  -0.33528254]
 [-3.7514455  -0.64299902 -2.82741584  1.02806984 -0.88630058  0.52791182]
 [-0.76771045  0.22977988 -0.44138948 -0.89628949  0.87157363 -0.16637099]
 [ 1.09217155 -1.15719505  2.63534405  2.43357403 -0.05327339  0.86451469]
 [-0.75089166 -0.363482   -0.58530784 -1.93498898 -0.64481942  0.3283395 ]]

True


#### LU Decomposition

In [7]:
pa,l,u = diag.plu()

In [8]:
print(pa,l,u,sep='\n\n')

[[ 1.68209386  0.70052075  0.18537211 -1.22226286  0.51384634 -0.73490155]
 [-0.46464491 -0.22186881 -1.83254945 -1.39994133 -0.24030872  0.15954438]
 [ 0.12170741  0.64829105  0.22680394 -1.25461459 -0.73704976 -0.16189788]]

[[ 1.          0.          0.        ]
 [ 1.          0.          0.        ]
 [-0.27623007  1.          0.        ]
 [-0.31671983  1.          0.        ]
 [ 0.07235471 -0.11979235  1.        ]
 [ 0.92544161  0.06909782  1.        ]]

[[ 1.68209386  0.18537211  0.51384634]
 [ 0.70052075 -1.22226286 -0.73490155]
 [ 0.         -1.7813441  -0.09836891]
 [ 0.         -1.78705621 -0.07321351]
 [ 0.          0.         -0.7860128 ]
 [ 0.          0.          0.52326948]]


#### Determinant

In [9]:
# Utilize existing U
diag.determinant(u)

1.5428094433056665

In [10]:
# requries LU decomposition
diag.permutation_flag = 1
diag.determinant() 

1.5428094433056665

In [11]:
np.linalg.det(sparse)

1.5428095

#### Solve + Inverse

In [12]:
b = np.eye(6)
x = diag.solve(b)

Lets check to make sure x is indeed the inverse

In [13]:
identity = np.dot(diag.to_sparse(pa),x)

In [14]:
print(identity,np.allclose(b,identity),sep='\n\n')

[[  1.00000000e+00   0.00000000e+00  -4.17966588e-18   0.00000000e+00
   -1.96151125e-17   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   4.63947772e-17
    0.00000000e+00  -4.01511616e-17]
 [ -6.02104757e-17   0.00000000e+00   1.00000000e+00   0.00000000e+00
   -3.26715166e-18   0.00000000e+00]
 [  0.00000000e+00  -5.03867806e-17   0.00000000e+00   1.00000000e+00
    0.00000000e+00  -2.60166964e-17]
 [  3.42193452e-19   0.00000000e+00  -1.33703472e-17   0.00000000e+00
    1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -1.90926808e-16   0.00000000e+00   1.66919518e-17
    0.00000000e+00   1.00000000e+00]]

True


#### Large Matrix Multiplication

The Diagonal class allows for a pre indexed matrix to perform matrix multiplication, which allows us to test the theoretical limit of the operation on the current device

In [15]:
diag = Diagonal(1000,1000)
x = np.random.randn(1000,1000,1000)

ax = diag.mm(x,batch=False)

In [16]:
print(ax.shape)

(1000000, 1000)
